### ISSUE TITLE
Errors running in Visual studio

### ISSUE THREAD

**Issue by IamBharaniKrishnan** [HYPJUDY/panorama-image-stitching#4]
Hi HYPJUDY,
I have downloaded your Image stitching project and run it through **Visual Studio 2015**. I get a bunch of errors. 

Those errors showing like
- LNK 2028, unresolved token,
- LNK 2019, unresolved external symbol,
- LNK 2011, precompiled object not linked in, image may not run,
- LNK 1120, unresolved externals.

**Comment by HYPJUDY** [comment]
It's hard to check errors with little info. Can you look for help from your nearby friends?

**Comment by RBKjobs** [comment]
Hi @HYPJUDY. I am totally dependent on your reply. I have no one to help right now. I am in a situation to use your source code in our product because I have tried everything like emgu cv etc. But no one have a support in 16 bit grayscale feature for stitching two images. So I just need to try out your code and hope to see it works.

Right now I have these two errors:

**Error	LNK2019	unresolved external symbol WinMain referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)**	
	
**Error	LNK1120	1 unresolved externals**

I followed all steps you gave in your blog but it creates generates lots of errors. I am basically from c# background so please help me out with these errors

Here is the screenshot of what I am getting.

![1](https://user-images.githubusercontent.com/40828211/42435272-9ebe7c36-8373-11e8-8c34-e0c1258993fb.png)

**Comment by IamBharaniKrishnan** [comment]
- Actually we are running your code in .NET framework 4.5.2. Are we setting it in right framework or do we need to change the framework? 
- We are using Visual Studio 2015
- Also do we need any external dependencies apart from downloading your source code.
- Do we need WinSDK(any external dependencies) to download for this?

Does the Target platform version right to run or do we need to change to 10. Please check the screenshot. We want clarity on whether we are setting the platform right or not. I am in needful of your help to complete my project. Please help me.

![1](https://user-images.githubusercontent.com/40828211/42496554-10bdc24e-8444-11e8-847e-44f8abea0191.png)

**Comment by IamBharaniKrishnan** [comment]
When I try to run throws exceptions. Please help me with this.

![1](https://user-images.githubusercontent.com/40828211/42451633-6a1c4526-83a5-11e8-886e-253fc48d80fa.png)

**Comment by HYPJUDY** [comment]
Hi, I run this code again. Here are my process.
I selected a custom install for VS15 and add C/C++ feature. Then I followed the instructions in readme. I also use the default .NET framework 4.5.2. Apart from configuring the dependencies mentioned in readme, I didn't do other things. Then I built successfully.
But I encountered the problem of missing `vcomp100.dll` when running (it can be solved by download one). I also encountered errors like `index out of range` in a function but not the same as yours.
It seems that this code is not robust and will throw different exceptions in different situations (it works well for me a year ago but not now). I haven't figure out your problem yet and if you works out please pull request to help me improve this project. Thanks!

**Comment by IamBharaniKrishnan** [comment]
Hi @HYPJUDY 
I have managed to run your code after a lot trial and error. Actually I tried to get 16 bit grayscale images stitched and given as an output from your code. But it's a tough luck, I can't stitch 16 bit grayscale image using your code.

As I am from c# background I find your code hard to run but somehow managed. It has some issues when I try to give image as an input as the function only picks up the first file and ignores other files. So one by one I tried to fix the issue. So that's it and finally I can't work with 16 bit grayscale images.

Can you please give any suggestions of any library that handle 16 bit images or any idea to make your code work for 16 bit grayscale images.

Thanks

**Comment by jingwu8023** [comment]
> When I try to run throws exceptions. Please help me with this.
> 
> ![1](https://user-images.githubusercontent.com/40828211/42451633-6a1c4526-83a5-11e8-886e-253fc48d80fa.png)

Hello, I have encountered the same situation as you, may I ask whether you have solved it?Can you help me solve it?
![image](https://user-images.githubusercontent.com/39717103/53419698-45b93280-3a15-11e9-85b0-5c6382097c7d.png)

**Comment by HYPJUDY** [comment]
See #5.
