### ISSUE TITLE
slove error running in Visual studio

### ISSUE THREAD

**Issue by jingwu8023** [HYPJUDY/panorama-image-stitching#5]
Because _findnext() returns intptr_t instead of long, the conversion from "intptr_t" to "long" loses data.So as long as the "long hFile" is changed to "intptr t hFile"

**Comment by HYPJUDY** [comment]
Hi, 
Could you share us what consequences would caused by the data loss?
Did you mean modify 
https://github.com/HYPJUDY/panorama-image-stitching/blob/5a2404d328c429be6d422f3ab36946d7196b21f4/utils.h#L46
to `intptr_t hFile = 0;`?
Have you tested this modification? If it works without other errors I will modify the code.
Thank you very much!

**Comment by jingwu8023** [comment]
yes，Although the last issue was resolved, another error occurred, and the output could not be saved.I'm debugging.
![image](https://user-images.githubusercontent.com/39717103/53534818-5bc11300-3b3b-11e9-810f-e49773babec5.png)

**Comment by jingwu8023** [comment]
yes，as long as the "long hFile" is changed to "intptr t hFile"，it works without other errors
[	https://github.com/HYPJUDY/panorama-image-stitching/blob/5a2404d328c429be6d422f3ab36946d7196b21f4/utils.h#L46](url)

**Comment by jingwu8023** [comment]
I have a question, why is it different every time?
![image](https://user-images.githubusercontent.com/39717103/53536242-8b264e80-3b40-11e9-8d1b-6f8e51533928.png)

**Comment by HYPJUDY** [comment]
I explained this in the third section "Results and Analysis" in [my post](https://hypjudy.github.io/2017/05/10/panorama-image-stitching/):

> Notice that in the RANSAC for estimating homography procedure, since four feature pairs are selected randomly for computing homography, we may obtain different results each run. Some results can be very bad due to one or several images’ distortion.
> The reason is the number of inliers is used as criteria for calculating homography transformation matrix H. “However, for high-resolution images, it’s common that you’ll actually find false matches with a considerable number of inliers, as long as enough RANSAC iterations are performed.”[5] Thus, after each matrix estimation, we should perform match validation check. I skip this part in my code currently and thus have a high chance of getting distorted stitched image when the number of source images is large.

Hope this helps.

**Comment by HYPJUDY** [comment]
Do you mean this modification can solve your problem in #4 ? Thanks!

**Comment by jingwu8023** [comment]
YES，Thank you for your explanation！
